### ISSUE TITLE
Create Cohort Lesson List View

### ISSUE THREAD

**Issue by ShaunLloyd** [bridge-school/content-dashboard#15]
### Value Statement
As a user I would like to see a list of saved and ongoing cohorts

### Acceptance Criteria
- [ ] Create a list page that displays saved and ongoing cohorts
- [ ] Cohorts can be hardcoded for now

### Mockup
![cohort-list-mockup](https://user-images.githubusercontent.com/18172605/39266015-cb426cbc-4896-11e8-8eb0-523b31d34a80.png)

**Comment by msukmanowsky** [comment]
This was merged in https://github.com/bridge-school/content-dashboard/pull/27 so closing out.
