### ISSUE TITLE
[BUG]: When you click on a cohort with modules it has a runtime error and the app crashes. See Screenshot

### ISSUE THREAD

**Issue by pkanal** [bridge-school/content-dashboard#55]
<img width="1065" alt="screen shot 2018-08-17 at 11 57 21 am" src="https://user-images.githubusercontent.com/8810222/44276372-3dd23780-a215-11e8-83b6-b7770695e6db.png">

**Comment by AnyaCraig** [comment]
Fix attempt in this PR: https://github.com/bridge-school/content-dashboard/pull/56
