### ISSUE TITLE
SPIKE: investigate how to implement slackbot that posts class outline for the next day

### ISSUE THREAD

**Issue by vanessamerritt** [bridge-school/content-dashboard#58]
AC

- Can we make a sb through firebase? do we need a node server?
- Tie chron job service

**Comment by vanessamerritt** [comment]
hi @ibarsi this is ready to be worked on OFFFFFICIALLY

**Comment by vanessamerritt** [comment]
<img width="598" alt="screen shot 2018-09-06 at 5 26 41 pm" src="https://user-images.githubusercontent.com/7038142/45186097-591fd980-b1fa-11e8-8db1-9f990a37350a.png">

**Comment by ibarsi** [comment]
@pkanal @AbdellaToronto 

Hey gang, got a few questions as I dig through this spike!

1. Is this a scheduled daily update on all upcoming classes for all cohorts, or is there only 1 cohort with 1 classroom at a time?
2. Are we only posting to a single channel?
3. Do we need slash command support?
4. Do we need interactive conversational support?

Side note, @AbdellaToronto could I get Firebase access?
